"""Step 12+ "Clinical Report" generator: assembles one patient's admission,
vitals, prediction history, SHAP explanation, and alert history into a
premium-formatted, print-ready PDF using reportlab -- the same data every
dashboard page (Step 9) already renders, just laid out for a clinician to
print or archive. Pure function of already-fetched data (no DB/HTTP calls in
here) so it's trivially unit-testable and reusable from any caller."""
import io
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

NAVY = colors.HexColor("#0b1f3a")
NAVY_LIGHT = colors.HexColor("#12315c")
TEAL = colors.HexColor("#0891b2")
INK = colors.HexColor("#111827")
MUTED = colors.HexColor("#6b7280")
FAINT = colors.HexColor("#9ca3af")
LINE = colors.HexColor("#e2e8f0")
PANEL = colors.HexColor("#f8fafc")

RISK_COLORS = {
    "Low": colors.HexColor("#0d9488"),
    "Medium": colors.HexColor("#ca8a04"),
    "High": colors.HexColor("#c2410c"),
    "Critical": colors.HexColor("#be123c"),
}

CORE_VITAL_CHANNELS = ["HR", "O2Sat", "Temp", "SBP", "MAP", "Resp"]
DISCLAIMER = (
    "Generated by an AI-based clinical decision-support system developed as part of a final-year "
    "academic project (Multi-Modal IoT & Deep Learning Framework for Early Prediction of Sepsis in "
    "Smart ICU Environments). This report is not a certified medical device and must not be used as "
    "the sole basis for a clinical decision -- always correlate with direct clinical assessment."
)


def _risk_color(risk_level: Optional[str]) -> colors.Color:
    return RISK_COLORS.get(risk_level or "", MUTED)


def _fmt_dt(value) -> str:
    if value is None:
        return "--"
    if isinstance(value, datetime):
        dt = value
    else:
        try:
            dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError:
            return str(value)
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("ReportTitle", parent=base["Title"], fontName="Helvetica-Bold",
                                  fontSize=17, textColor=colors.white, leading=20, alignment=TA_LEFT),
        "subtitle": ParagraphStyle("ReportSubtitle", parent=base["Normal"], fontName="Helvetica",
                                     fontSize=9.5, textColor=colors.HexColor("#bcd2ee"), leading=12),
        "meta": ParagraphStyle("ReportMeta", parent=base["Normal"], fontName="Helvetica",
                                 fontSize=8.5, textColor=colors.white, alignment=TA_RIGHT, leading=12),
        "section": ParagraphStyle("Section", parent=base["Heading2"], fontName="Helvetica-Bold",
                                    fontSize=11.5, textColor=NAVY, spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontName="Helvetica", fontSize=9,
                                 textColor=INK, leading=13),
        "muted": ParagraphStyle("Muted", parent=base["Normal"], fontName="Helvetica", fontSize=8.5,
                                  textColor=MUTED, leading=12),
        "cell": ParagraphStyle("Cell", parent=base["Normal"], fontName="Helvetica", fontSize=8,
                                 textColor=INK, leading=11),
        "cell_head": ParagraphStyle("CellHead", parent=base["Normal"], fontName="Helvetica-Bold",
                                      fontSize=7.5, textColor=colors.white, leading=10),
        "risk_value": ParagraphStyle("RiskValue", parent=base["Normal"], fontName="Helvetica-Bold",
                                       fontSize=22, textColor=colors.white, alignment=TA_CENTER, leading=24),
        "risk_label": ParagraphStyle("RiskLabel", parent=base["Normal"], fontName="Helvetica",
                                       fontSize=8, textColor=colors.white, alignment=TA_CENTER, leading=10),
        "disclaimer": ParagraphStyle("Disclaimer", parent=base["Normal"], fontName="Helvetica-Oblique",
                                       fontSize=6.8, textColor=FAINT, leading=9),
    }


def _kv_grid(pairs: list[tuple[str, str]], styles: dict, col_widths) -> Table:
    rows = []
    for i in range(0, len(pairs), 2):
        row = []
        for label, value in pairs[i:i + 2]:
            row.append(Paragraph(f'<font color="#6b7280">{label}</font><br/>{value}', styles["body"]))
        if len(row) == 1:
            row.append("")
        rows.append(row)
    table = Table(rows, colWidths=col_widths, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PANEL),
        ("BOX", (0, 0), (-1, -1), 0.75, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table


def _risk_panel(risk_level: Optional[str], probability: Optional[float], model_version: str, assessed_at, styles: dict) -> Table:
    color = _risk_color(risk_level)
    prob_text = f"{probability:.1%}" if probability is not None else "--"
    left = Table([
        [Paragraph((risk_level or "UNKNOWN").upper(), styles["risk_value"])],
        [Paragraph("CURRENT RISK LEVEL", styles["risk_label"])],
    ], colWidths=[55 * mm])
    left.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), color),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, 0), 12),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 10),
    ]))

    right = Table([
        [Paragraph('<font color="#6b7280">Sepsis probability</font>', styles["body"]),
         Paragraph(f"<b>{prob_text}</b>", styles["body"])],
        [Paragraph('<font color="#6b7280">Model version</font>', styles["body"]),
         Paragraph(model_version or "--", styles["body"])],
        [Paragraph('<font color="#6b7280">Assessed at</font>', styles["body"]),
         Paragraph(_fmt_dt(assessed_at), styles["body"])],
    ], colWidths=[38 * mm, 62 * mm])
    right.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))

    outer = Table([[left, right]], colWidths=[58 * mm, 102 * mm])
    outer.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.75, LINE),
        ("BACKGROUND", (1, 0), (1, 0), PANEL),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (1, 0), (1, 0), 10),
    ]))
    return outer


def _data_table(headers: list[str], rows: list[list[str]], col_widths, styles: dict, empty_message: str) -> Table:
    if not rows:
        return Paragraph(empty_message, styles["muted"])

    header_row = [Paragraph(h, styles["cell_head"]) for h in headers]
    body_rows = [[Paragraph(str(v), styles["cell"]) for v in row] for row in rows]
    table = Table([header_row] + body_rows, colWidths=col_widths, repeatRows=1, hAlign="LEFT")
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY_LIGHT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("LINEBELOW", (0, 0), (-1, 0), 0.75, NAVY_LIGHT),
        ("LINEBELOW", (0, 1), (-1, -1), 0.5, LINE),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for i in range(1, len(body_rows) + 1):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), PANEL))
    table.setStyle(TableStyle(style))
    return table


def build_patient_report_pdf(
    patient: dict,
    vitals_history: list[dict],
    prediction_history: list[dict],
    shap_explanation: Optional[dict],
    alerts: list[dict],
    generated_at: Optional[datetime] = None,
    max_rows: int = 12,
) -> bytes:
    """Renders the full clinical PDF report and returns the raw bytes.
    All inputs are already-fetched, JSON-shaped data (as returned by the
    dashboard's ApiClient / the FastAPI schemas) -- this function does no I/O."""
    generated_at = generated_at or datetime.now(timezone.utc)
    styles = _styles()
    patient_id = patient.get("patient_id", "unknown")

    predictions_sorted = sorted(prediction_history, key=lambda p: p.get("created_at") or "", reverse=True)
    latest_prediction = predictions_sorted[0] if predictions_sorted else None
    vitals_sorted = sorted(vitals_history, key=lambda v: v.get("timestamp") or "", reverse=True)
    alerts_sorted = sorted(alerts, key=lambda a: a.get("created_at") or "", reverse=True)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=32 * mm, bottomMargin=16 * mm, leftMargin=16 * mm, rightMargin=16 * mm,
        title=f"Sepsis Risk Report - {patient_id}", author="Sepsis ICU Monitor",
    )

    story = []

    story.append(Paragraph("Patient Snapshot", styles["section"]))
    story.append(_kv_grid([
        ("Patient ID", patient_id),
        ("Source dataset", patient.get("source_dataset", "--")),
        ("Age", str(patient.get("age")) if patient.get("age") is not None else "--"),
        ("Sex", patient.get("sex") or "--"),
        ("Unit admitted", patient.get("unit_admitted") or "--"),
        ("Status", (patient.get("current_status") or "--").capitalize()),
        ("Admission time", _fmt_dt(patient.get("admission_time"))),
        ("Report generated", _fmt_dt(generated_at)),
    ], styles, col_widths=[85 * mm, 75 * mm]))

    story.append(Paragraph("Current Risk Assessment", styles["section"]))
    if latest_prediction:
        story.append(_risk_panel(
            latest_prediction.get("risk_level"), latest_prediction.get("sepsis_probability"),
            latest_prediction.get("model_version", "--"), latest_prediction.get("created_at"), styles,
        ))
    else:
        story.append(Paragraph("No prediction has been recorded for this patient yet.", styles["muted"]))

    story.append(Paragraph("Recent Vitals", styles["section"]))
    vitals_rows = [
        [_fmt_dt(v.get("timestamp")), v.get("source", "--")] +
        [("--" if v.get("channels", {}).get(c) is None else f"{v['channels'][c]:.1f}") for c in CORE_VITAL_CHANNELS]
        for v in vitals_sorted[:max_rows]
    ]
    story.append(_data_table(
        ["Time", "Source"] + CORE_VITAL_CHANNELS, vitals_rows,
        col_widths=[28 * mm, 22 * mm] + [(160 - 50) / len(CORE_VITAL_CHANNELS) * mm] * len(CORE_VITAL_CHANNELS),
        styles=styles, empty_message="No vitals recorded yet for this patient.",
    ))

    story.append(Paragraph("Prediction Trend", styles["section"]))
    prediction_rows = [
        [_fmt_dt(p.get("created_at")), f"{p.get('sepsis_probability', 0):.1%}", p.get("risk_level", "--"), p.get("model_version", "--")]
        for p in predictions_sorted[:max_rows]
    ]
    story.append(_data_table(
        ["Time", "Probability", "Risk Level", "Model Version"], prediction_rows,
        col_widths=[38 * mm, 32 * mm, 30 * mm, 60 * mm], styles=styles,
        empty_message="No predictions have been recorded for this patient yet.",
    ))

    story.append(Paragraph("Explainability (Top Contributing Channels)", styles["section"]))
    top_features = (shap_explanation or {}).get("top_contributing_features") or []
    shap_rows = [
        [f.get("feature", "--"), f"{f.get('value', 0):.2f}",
         f"{f.get('contribution', 0):+.4f}", "Increases risk" if f.get("contribution", 0) > 0 else "Decreases risk"]
        for f in top_features
    ]
    story.append(_data_table(
        ["Channel", "Observed Value", "SHAP Contribution", "Direction"], shap_rows,
        col_widths=[38 * mm, 38 * mm, 38 * mm, 46 * mm], styles=styles,
        empty_message="No SHAP explanation is available yet for this patient's latest prediction.",
    ))

    story.append(Paragraph("Alert History", styles["section"]))
    alert_rows = [
        [_fmt_dt(a.get("created_at")), a.get("risk_level", "--"), a.get("message", "--"),
         (f"Ack'd by {a['acknowledged_by']}" if a.get("acknowledged") else "Unacknowledged")]
        for a in alerts_sorted[:max_rows]
    ]
    story.append(_data_table(
        ["Time", "Risk", "Message", "Status"], alert_rows,
        col_widths=[32 * mm, 20 * mm, 78 * mm, 32 * mm], styles=styles,
        empty_message="No alerts have been raised for this patient.",
    ))

    story.append(Spacer(1, 10 * mm))
    story.append(KeepTogether([Paragraph(DISCLAIMER, styles["disclaimer"])]))

    def _draw_page_frame(canvas, _doc):
        canvas.saveState()
        canvas.setFillColor(NAVY)
        canvas.rect(0, A4[1] - 26 * mm, A4[0], 26 * mm, stroke=0, fill=1)
        canvas.setFillColor(TEAL)
        canvas.rect(0, A4[1] - 26.5 * mm, A4[0], 0.5 * mm, stroke=0, fill=1)

        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 15)
        canvas.drawString(16 * mm, A4[1] - 12 * mm, "Sepsis ICU Monitor")
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor(colors.HexColor("#bcd2ee"))
        canvas.drawString(16 * mm, A4[1] - 18 * mm, "Clinical Risk Report -- Multi-Modal IoT & Deep Learning Sepsis Prediction")

        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 11)
        canvas.drawRightString(A4[0] - 16 * mm, A4[1] - 12 * mm, f"Patient {patient_id}")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#bcd2ee"))
        canvas.drawRightString(A4[0] - 16 * mm, A4[1] - 18 * mm, _fmt_dt(generated_at))

        canvas.setStrokeColor(LINE)
        canvas.line(16 * mm, 12 * mm, A4[0] - 16 * mm, 12 * mm)
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawString(16 * mm, 7 * mm, "Sepsis ICU Monitor -- AI decision-support system, not a certified medical device")
        canvas.drawRightString(A4[0] - 16 * mm, 7 * mm, f"Page {canvas.getPageNumber()}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_draw_page_frame, onLaterPages=_draw_page_frame)
    return buffer.getvalue()
